/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diagsys;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingWorker;

/**
 *
 * @author Mr Olayinka
 */
public final class DNView_1 extends javax.swing.JDialog {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stmt = null;
    String typ = "Typhoid Fever";
    String mal = "Malaria";
    String gast = "Gastroenteritis";

    /**
     * Creates new form NewJDialog
     *
     * @param parent
     * @param modal
     */
    public DNView_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
       // jLabel2.setIcon(new ImageIcon("src/progressbg_green.gif"));
        jLabel1.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doctor/Nurse Record");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fever", "Weakness", "Headache", "MusclePain", "joint pain", "Lackofappetite", "Diarrhea", "Nausea ", "Vomiting", "Abdominalpain", "Cold ", "Constipation", "Cough", "Fatigue", "Tiredness", " ", " " }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fever", "Weakness", "Headache", "MusclePain", "joint pain", "Lackofappetite", "Diarrhea", "Nausea ", "Vomiting", "Abdominalpain", "Cold ", "Constipation", "Cough", "Fatigue", "Tiredness", " " }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fever", "Weakness", "Headache", "MusclePain", "joint pain", "Lackofappetite", "Diarrhea", "Nausea ", "Vomiting", "Abdominalpain", "Cold ", "Constipation", "Cough", "Fatigue", "Tiredness", " " }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fever", "Weakness", "Headache", "MusclePain", "joint pain", "Lackofappetite", "Diarrhea", "Nausea ", "Vomiting", "Abdominalpain", "Cold ", "Constipation", "Cough", "Fatigue", "Tiredness", " " }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fever", "Weakness", "Headache", "MusclePain", "joint pain", "Lackofappetite", "Diarrhea", "Nausea ", "Vomiting", "Abdominalpain", "Cold ", "Constipation", "Cough", "Fatigue", "Tiredness", " " }));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(307, Short.MAX_VALUE)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         //  try { 
        // TODO add your handling code here:
        String input = jComboBox3.getSelectedItem().toString().trim() + " "
                + jComboBox2.getSelectedItem().toString().trim() + " "
                + jComboBox5.getSelectedItem().toString().trim() + " "
                + jComboBox8.getSelectedItem().toString().trim() + " "
                + jComboBox9.getSelectedItem().toString().trim();
////               
        List<String> list = new ArrayList<>(Arrays.asList(input.trim().split(" ")));
        HashMap<String, String> hash = new HashMap<>();
        for (String list1 : list) {
            hash.put(list1, list1);
        }
        if ( (hash.containsKey("Vomiting")) && (hash.containsKey("Fever")) && (hash.containsKey("Headache")) && (hash.containsKey("Tiredness"))
                 && (hash.containsKey("Diarrhea"))) {
            jLabel1.setText(gast);
            try {
             

                Progress();
            } catch (InterruptedException ex) {
                Logger.getLogger(DNView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (hash.containsKey("Fever") && hash.containsKey("Headache") && hash.containsKey("Abdominalpain") && hash.containsKey("Constipation") || hash.containsKey("Cough")
                && hash.containsKey("Diarrhea") || hash.containsKey("Lackofappetite") || hash.containsKey("Fatigue") || hash.containsKey("Chills")) {
            jLabel1.setText(typ);
            try {

                Progress();
            } catch (InterruptedException ex) {
                Logger.getLogger(DNView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

////        
        /**
         * Declare the rule
         */
//        HelloWorldRule helloWorldRule = new HelloWorldRule();
//
//        /**
//         * Set business data to operate on
//         */
//        helloWorldRule.setInput(input);
//     
//
//        /**
//         * Create a rules engine and register the business rule
//         */
//        RulesEngine rulesEngine = aNewRulesEngine()
//                .named("Gast")
//                
//                .build();
//
//        rulesEngine.registerRule(helloWorldRule);
//
//        /**
//         * Fire rules
//         */
//        rulesEngine.fireRules();
        System.err.println(input);
        System.err.println(list);
//////               
////               String Voicename = "kevin16";
////            VoiceManager V = VoiceManager.getInstance();
////            Voice voice = V.getVoice(Voicename);
////            voice.allocate();
////            String fn;
////               con = SqlConnect.conDB();
////               stmt = con.createStatement();
////               String o =  "select Disease from Base where Symptoms like'%"+input+"%' " ;
////                rs = stmt.executeQuery(o);
////                if (rs.next()){
////                
////                  fn = rs.getString("Disease");
////                    jTextField1.setText(fn);
////                    voice.speak("Your Disease is "+ fn);
////                }
////                else{ JOptionPane.showMessageDialog(null, "No Disease Matches Your Symptoms", "Symptoms ", JOptionPane.INFORMATION_MESSAGE);}
////               
////           }catch (SQLException |IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
////            JOptionPane.showMessageDialog(null, ex);
////        }  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DNView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DNView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DNView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DNView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DNView_1 dialog = new DNView_1 (new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

   
    public void Progress() throws InterruptedException {

        final JFrame g = new JFrame();
        g.setUndecorated(true);
        g.setSize(180, 46);
        ImageIcon icon = new ImageIcon("src/wait.gif");
        g.add(new JLabel(" Diagnosis in progress...", icon, JLabel.CENTER));
        g.setLocationRelativeTo(null);

        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws Exception {
                Thread.sleep(5000);

                jTextField1.setText(jLabel1.getText());
                return null;
            }

            @Override
            protected void done() {

                g.dispose();
            }

        };
        worker.execute();
              g.setVisible(true);

    }
}
