/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package diagsys;

import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Mr Olayinka
 */
public class Knowledge extends javax.swing.JDialog {

    /**
     * Creates new form Drugs
     * @param parent
     * @param modal
     */
    Connection conn = null;
      ResultSet rs = null;
      Statement st =null;
      PreparedStatement pst =null;
      
    public Knowledge(java.awt.Frame parent, boolean modal) throws ClassNotFoundException, SQLException, InstantiationException, IOException, IllegalAccessException {
        super(parent, modal);
        initComponents();
        jLabel1.setVisible(false);
        data();
        setLocationRelativeTo(null);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        Parentpanel = new javax.swing.JPanel();
        M_about = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneMA = new javax.swing.JTextPane();
        Malabtupdate = new javax.swing.JButton();
        M_preventions = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneMP = new javax.swing.JTextPane();
        Malpreupdate = new javax.swing.JButton();
        M_drug = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPaneMD = new javax.swing.JTextPane();
        Maldrugupdate = new javax.swing.JButton();
        T_about = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPaneTA = new javax.swing.JTextPane();
        Tyabtupdate = new javax.swing.JButton();
        T_preventions = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPaneTP = new javax.swing.JTextPane();
        Typreupdate = new javax.swing.JButton();
        T_drug = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPaneTD = new javax.swing.JTextPane();
        Tydrugupdate = new javax.swing.JButton();
        G_about = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPaneGA = new javax.swing.JTextPane();
        Gasabtupdate = new javax.swing.JButton();
        G_preventions = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPaneGP = new javax.swing.JTextPane();
        Gaspreupdate = new javax.swing.JButton();
        G_drug = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPaneGD = new javax.swing.JTextPane();
        Gasdrugupdate = new javax.swing.JButton();
        yo = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        Malariadesclbl = new javax.swing.JTextArea();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Knowledge On Diseases");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setPreferredSize(new java.awt.Dimension(640, 431));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Diseases");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Malaria");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("M-about");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("M-preventions");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("M-drug");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Typhoid Fever");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("T-about");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("T-preventions");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("T-drug");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gastroenteritis");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("G-about");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("G-preventions");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("G-drug");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Parentpanel.setLayout(new java.awt.CardLayout());

        jTextPaneMA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(jTextPaneMA);

        Malabtupdate.setText("Update ");
        Malabtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalabtupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout M_aboutLayout = new javax.swing.GroupLayout(M_about);
        M_about.setLayout(M_aboutLayout);
        M_aboutLayout.setHorizontalGroup(
            M_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
            .addGroup(M_aboutLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(Malabtupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        M_aboutLayout.setVerticalGroup(
            M_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Malabtupdate)
                .addContainerGap())
        );

        Parentpanel.add(M_about, "card10");

        jTextPaneMP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(jTextPaneMP);

        Malpreupdate.setText("Update Preventions");
        Malpreupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalpreupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout M_preventionsLayout = new javax.swing.GroupLayout(M_preventions);
        M_preventions.setLayout(M_preventionsLayout);
        M_preventionsLayout.setHorizontalGroup(
            M_preventionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_preventionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
            .addGroup(M_preventionsLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(Malpreupdate)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        M_preventionsLayout.setVerticalGroup(
            M_preventionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_preventionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Malpreupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Parentpanel.add(M_preventions, "card4");

        jTextPaneMD.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(jTextPaneMD);

        Maldrugupdate.setText("Update Drugs");
        Maldrugupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaldrugupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout M_drugLayout = new javax.swing.GroupLayout(M_drug);
        M_drug.setLayout(M_drugLayout);
        M_drugLayout.setHorizontalGroup(
            M_drugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_drugLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
            .addGroup(M_drugLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(Maldrugupdate)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        M_drugLayout.setVerticalGroup(
            M_drugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_drugLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Maldrugupdate)
                .addContainerGap())
        );

        Parentpanel.add(M_drug, "card5");

        jTextPaneTA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(jTextPaneTA);

        Tyabtupdate.setText("Update ");
        Tyabtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TyabtupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_aboutLayout = new javax.swing.GroupLayout(T_about);
        T_about.setLayout(T_aboutLayout);
        T_aboutLayout.setHorizontalGroup(
            T_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
            .addGroup(T_aboutLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(Tyabtupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        T_aboutLayout.setVerticalGroup(
            T_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tyabtupdate)
                .addContainerGap())
        );

        Parentpanel.add(T_about, "card5");

        jTextPaneTP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane7.setViewportView(jTextPaneTP);

        Typreupdate.setText("Update Preventions");
        Typreupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypreupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_preventionsLayout = new javax.swing.GroupLayout(T_preventions);
        T_preventions.setLayout(T_preventionsLayout);
        T_preventionsLayout.setHorizontalGroup(
            T_preventionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_preventionsLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(Typreupdate)
                .addGap(0, 153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T_preventionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7))
        );
        T_preventionsLayout.setVerticalGroup(
            T_preventionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_preventionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Typreupdate)
                .addContainerGap())
        );

        Parentpanel.add(T_preventions, "card6");

        jTextPaneTD.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane8.setViewportView(jTextPaneTD);

        Tydrugupdate.setText("Update Drugs");
        Tydrugupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TydrugupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout T_drugLayout = new javax.swing.GroupLayout(T_drug);
        T_drug.setLayout(T_drugLayout);
        T_drugLayout.setHorizontalGroup(
            T_drugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_drugLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
            .addGroup(T_drugLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(Tydrugupdate)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        T_drugLayout.setVerticalGroup(
            T_drugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T_drugLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tydrugupdate)
                .addContainerGap())
        );

        Parentpanel.add(T_drug, "card7");

        jTextPaneGA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane9.setViewportView(jTextPaneGA);

        Gasabtupdate.setText("Update ");
        Gasabtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GasabtupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout G_aboutLayout = new javax.swing.GroupLayout(G_about);
        G_about.setLayout(G_aboutLayout);
        G_aboutLayout.setHorizontalGroup(
            G_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G_aboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Gasabtupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        G_aboutLayout.setVerticalGroup(
            G_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gasabtupdate)
                .addContainerGap())
        );

        Parentpanel.add(G_about, "card7");

        jTextPaneGP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane10.setViewportView(jTextPaneGP);

        Gaspreupdate.setText("Update Preventions");
        Gaspreupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaspreupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout G_preventionsLayout = new javax.swing.GroupLayout(G_preventions);
        G_preventions.setLayout(G_preventionsLayout);
        G_preventionsLayout.setHorizontalGroup(
            G_preventionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_preventionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G_preventionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Gaspreupdate)
                .addGap(148, 148, 148))
        );
        G_preventionsLayout.setVerticalGroup(
            G_preventionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_preventionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gaspreupdate)
                .addContainerGap())
        );

        Parentpanel.add(G_preventions, "card6");

        jTextPaneGD.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane11.setViewportView(jTextPaneGD);

        Gasdrugupdate.setText("Update Drugs");
        Gasdrugupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GasdrugupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout G_drugLayout = new javax.swing.GroupLayout(G_drug);
        G_drug.setLayout(G_drugLayout);
        G_drugLayout.setHorizontalGroup(
            G_drugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G_drugLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11))
            .addGroup(G_drugLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(Gasdrugupdate)
                .addGap(0, 175, Short.MAX_VALUE))
        );
        G_drugLayout.setVerticalGroup(
            G_drugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_drugLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gasdrugupdate)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Parentpanel.add(G_drug, "card5");

        Malariadesclbl.setBackground(new java.awt.Color(204, 204, 255));
        Malariadesclbl.setColumns(20);
        Malariadesclbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Malariadesclbl.setRows(5);
        jScrollPane12.setViewportView(Malariadesclbl);

        javax.swing.GroupLayout yoLayout = new javax.swing.GroupLayout(yo);
        yo.setLayout(yoLayout);
        yoLayout.setHorizontalGroup(
            yoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(jScrollPane12))
                .addContainerGap())
        );
        yoLayout.setVerticalGroup(
            yoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Parentpanel.add(yo, "card11");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:

        
        DefaultMutableTreeNode sn ;
        sn = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        if (sn!=null) {
            jLabel1.setText(sn.toString());
            switch (jLabel1.getText()) {
                case "M-about":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(M_about);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                case "M-preventions":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(M_preventions);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                case "M-drug":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(M_drug);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;

                case "T-about":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(T_about);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                case "T-preventions":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(T_preventions);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                case "T-drug":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(T_drug);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;

                case "G-about":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(G_about);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                case "G-preventions":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(G_preventions);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                case "G-drug":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                Parentpanel.add(G_drug);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;

                case "Diseases":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                     
                case "Malaria":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                NewClass.LoadIntoMalariaPanel();
                Parentpanel.add(yo);
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                case "Typhoid Fever":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                case "Gastroenteritis":
                Parentpanel.removeAll();
                Parentpanel.repaint();
                Parentpanel.revalidate();
                break;
                    
            }
        }
    }//GEN-LAST:event_jTree1ValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void GasdrugupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GasdrugupdateActionPerformed
        // TODO add your handling code here:
         try{

            conn = SqlConnect.conDB();

            String add = "update Aboutdisease set Gastro_drug=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneGD.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Gastroenteritis drugs Successfully Updated");
            //data();
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }
    }//GEN-LAST:event_GasdrugupdateActionPerformed

    private void GaspreupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaspreupdateActionPerformed
        // TODO add your handling code here:
         try{

            conn = SqlConnect.conDB();

            String add = "update Aboutdisease set Gastro_prevention=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneGP.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Gastroenteritis Prevention Successfully Updated");
            //data();
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }
    }//GEN-LAST:event_GaspreupdateActionPerformed

    private void GasabtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GasabtupdateActionPerformed
        // TODO add your handling code here:
        try{

            conn = SqlConnect.conDB();
            String add = "update Aboutdisease set Gastro_about=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneGA.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, " About Gastroenteritis Successfully Updated");
            //data();
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }

    }//GEN-LAST:event_GasabtupdateActionPerformed

    private void TydrugupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TydrugupdateActionPerformed
        // TODO add your handling code here:
        try{

            conn = SqlConnect.conDB();
            String add = "update Aboutdisease set Typhoid_drug=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneTD.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "TyphoidFever drugs Successfully Updated");
           
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }
    }//GEN-LAST:event_TydrugupdateActionPerformed

    private void TypreupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypreupdateActionPerformed
        // TODO add your handling code here:
         try{

            conn = SqlConnect.conDB();
            String add = "update Aboutdisease set Typhoid_prevention=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneTP.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "TyphoidFever Prevention Successfully Updated");
            //data();
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }
    }//GEN-LAST:event_TypreupdateActionPerformed

    private void TyabtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TyabtupdateActionPerformed
        // TODO add your handling code here:
        try{

            conn = SqlConnect.conDB();
            String add = "update Aboutdisease set Typhoid_about=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneTA.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, " About TyphoidFever Successfully Updated");
            //data();
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }
    }//GEN-LAST:event_TyabtupdateActionPerformed

    private void MaldrugupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaldrugupdateActionPerformed
        // TODO add your handling code here:
         try{

            conn = SqlConnect.conDB();
            String add = "update Aboutdisease set Malaria_drug=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneMD.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Malaria Drug Successfully Updated");
            //data();
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }
    }//GEN-LAST:event_MaldrugupdateActionPerformed

    private void MalpreupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalpreupdateActionPerformed
        // TODO add your handling code here:
        try{

            conn = SqlConnect.conDB();
            String add = "update Aboutdisease set Malaria_prevention=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneMP.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Malaria Prevention Successfully Updated");
            //data();
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }
    }//GEN-LAST:event_MalpreupdateActionPerformed

    private void MalabtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalabtupdateActionPerformed
        // TODO add your handling code here:
        try{

            conn = SqlConnect.conDB();
            String add = "update Aboutdisease set Malaria_about=? ";
            pst = conn.prepareStatement(add);
            pst.setString(1, jTextPaneMA.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "About Malaria Successfully Updated");
            //data();
            pst.close();
       
        }catch(HeadlessException | SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex){
            JOptionPane.showMessageDialog(this,ex);
        } finally{
            if (conn!= null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

         }
    }//GEN-LAST:event_MalabtupdateActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Knowledge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Knowledge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Knowledge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Knowledge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Knowledge dialog = new Knowledge(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (ClassNotFoundException | SQLException | InstantiationException | IOException | IllegalAccessException ex) {
                    Logger.getLogger(Knowledge.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel G_about;
    private javax.swing.JPanel G_drug;
    private javax.swing.JPanel G_preventions;
    public static javax.swing.JButton Gasabtupdate;
    public static javax.swing.JButton Gasdrugupdate;
    public static javax.swing.JButton Gaspreupdate;
    private javax.swing.JPanel M_about;
    public static javax.swing.JPanel M_drug;
    private javax.swing.JPanel M_preventions;
    public static javax.swing.JButton Malabtupdate;
    public static javax.swing.JTextArea Malariadesclbl;
    public static javax.swing.JButton Maldrugupdate;
    public static javax.swing.JButton Malpreupdate;
    private javax.swing.JPanel Parentpanel;
    private javax.swing.JPanel T_about;
    private javax.swing.JPanel T_drug;
    private javax.swing.JPanel T_preventions;
    public static javax.swing.JButton Tyabtupdate;
    public static javax.swing.JButton Tydrugupdate;
    public static javax.swing.JButton Typreupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane1;
    public static javax.swing.JTextPane jTextPaneGA;
    public static javax.swing.JTextPane jTextPaneGD;
    public static javax.swing.JTextPane jTextPaneGP;
    public static javax.swing.JTextPane jTextPaneMA;
    public static javax.swing.JTextPane jTextPaneMD;
    public static javax.swing.JTextPane jTextPaneMP;
    public static javax.swing.JTextPane jTextPaneTA;
    public static javax.swing.JTextPane jTextPaneTD;
    public static javax.swing.JTextPane jTextPaneTP;
    private javax.swing.JTree jTree1;
    public static javax.swing.JLabel pic;
    public static javax.swing.JPanel yo;
    // End of variables declaration//GEN-END:variables

public void data() throws ClassNotFoundException, SQLException, IOException, FileNotFoundException, InstantiationException, IllegalAccessException{

    
         String Malaria_about;
         String Malaria_prevention;
         String Malaria_drug;
         String Typhoid_about;
         String Typhoid_prevention;
         String Typhoid_drug;
         String Gastro_about;
         String Gastro_prevention;
         String Gastro_drug;
                    
         conn = SqlConnect.conDB();
                        st = conn.createStatement();
                        rs = st.executeQuery("select * from Aboutdisease ");
                     while(rs.next()){

                    Malaria_about = rs.getString("Malaria_about");  
                    Malaria_prevention = rs.getString("Malaria_prevention");  
                    Malaria_drug = rs.getString("Malaria_drug");  
                    Typhoid_about = rs.getString("Typhoid_about");  
                    Typhoid_prevention = rs.getString("Typhoid_prevention");  
                    Typhoid_drug = rs.getString("Typhoid_drug");  
                    Gastro_about = rs.getString("Gastro_about");  
                    Gastro_prevention = rs.getString("Gastro_prevention");  
                    Gastro_drug = rs.getString("Gastro_drug");  
                    
                 jTextPaneMA.setText(Malaria_about);
                jTextPaneMP.setText(Malaria_prevention);
                 jTextPaneMD.setText(Malaria_drug);
                 jTextPaneTA.setText(Typhoid_about);
                 jTextPaneTP.setText(Typhoid_prevention);
                 jTextPaneTD.setText( Typhoid_drug);
                jTextPaneGA.setText(Gastro_about);
                 jTextPaneGP.setText(Gastro_prevention);
                 jTextPaneGD.setText(Gastro_drug);
                 
                 
            }
                     

                        rs.close();  
                        st.close();
      
 
    }

}
 
//        Toolkit t = Toolkit.getDefaultToolkit();
//        Dimension dim = new Dimension(t.getScreenSize());
//                int h = (int) dim.getHeight();
//                int w= (int) dim.getWidth();
//                setSize(w,h);
//                setLocation(w/2 - getWidth() / 2, h/2 - getHeight()/2);

