/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diagsys;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;

/**
 *
 * @author AJIBOLA
 */
public class Prescription extends javax.swing.JDialog {

    /**
     * Creates new form Prescription
     */
    Connection con=null;
     PreparedStatement pst=null;
     ResultSet rs = null;
      Statement st =null;
   
    
    public Prescription(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        LoadPrescriptions();
         UpdateGastpre.setBackground(Color.PINK);
          UpdateMalpre.setBackground(Color.PINK);
           UpdateTyphpre.setBackground(Color.PINK);
             jPanel3.setBackground(Color.decode("#66424d"));
               jPanel2.setBackground(Color.decode("#66424d"));
                 jPanel1.setBackground(Color.decode("#66424d"));
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Malpres = new javax.swing.JTextPane();
        UpdateMalpre = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Typhpres = new javax.swing.JTextPane();
        UpdateTyphpre = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Gastpres = new javax.swing.JTextPane();
        UpdateGastpre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prescription");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setViewportView(Malpres);

        UpdateMalpre.setText("Update");
        UpdateMalpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMalpreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 200, Short.MAX_VALUE)
                        .addComponent(UpdateMalpre)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateMalpre)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Malaria", jPanel1);

        jScrollPane2.setViewportView(Typhpres);

        UpdateTyphpre.setText("Update");
        UpdateTyphpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTyphpreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 200, Short.MAX_VALUE)
                        .addComponent(UpdateTyphpre)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateTyphpre)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Typhoid Fever", jPanel2);

        jScrollPane3.setViewportView(Gastpres);

        UpdateGastpre.setText("Update");
        UpdateGastpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateGastpreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(UpdateGastpre)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateGastpre)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gastroenteritis", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateTyphpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTyphpreActionPerformed
        // TODO add your handling code here:
        Prescribe("Typhoid Fever",Typhpres);
        
    }//GEN-LAST:event_UpdateTyphpreActionPerformed

    private void UpdateMalpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMalpreActionPerformed
        // TODO add your handling code here:
        Prescribe("Malaria",Malpres);
        
    }//GEN-LAST:event_UpdateMalpreActionPerformed

    private void UpdateGastpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateGastpreActionPerformed
        // TODO add your handling code here:
        Prescribe("Gastroenteritis",Gastpres);
    }//GEN-LAST:event_UpdateGastpreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Prescription dialog = new Prescription(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Gastpres;
    private javax.swing.JTextPane Malpres;
    private javax.swing.JTextPane Typhpres;
    private javax.swing.JButton UpdateGastpre;
    private javax.swing.JButton UpdateMalpre;
    private javax.swing.JButton UpdateTyphpre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public final void Prescribe(String diseaseName, JTextPane TPname) {
        try {
 
          con = SqlConnect.conDB();
            String add = "update Base set prescription=? where disease ='"+diseaseName+"' ";
            pst = con.prepareStatement(add);
            pst.setString(1, TPname.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Prescription Updated");
            
            pst.close();     
           
        } catch (SQLException | ClassNotFoundException | IOException | InstantiationException| IllegalAccessException ex) {
            Logger.getLogger(Diagnosis.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
          }


    
    public final void LoadPrescriptions() {

    
        try {
            
            String Malaria_prescription;
            String Typhoid_prescription;
            String Gastro_prescription;
            
            
            con = SqlConnect.conDB();
            st = con.createStatement();
            
            String malpres = "select prescription from Base where disease ='Malaria' ";
            String Typhoidpres = "select prescription from Base where disease ='Typhoid Fever' ";
            String Gastropres = "select prescription from Base where disease ='Gastroenteritis' ";
            
            rs = st.executeQuery(malpres);
            while(rs.next()){
                
                Malaria_prescription = rs.getString("prescription");
                Malpres.setText(Malaria_prescription);
                
            }
            
            rs = st.executeQuery(Typhoidpres);
            while(rs.next()){
                Typhoid_prescription = rs.getString("prescription");
                Typhpres.setText(Typhoid_prescription);
            }
            
            rs = st.executeQuery(Gastropres);
            while(rs.next()){
                Gastro_prescription = rs.getString("prescription");
                Gastpres.setText(Gastro_prescription);
            }
            
            rs.close();
            st.close();
        } catch (SQLException | IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Prescription.class.getName()).log(Level.SEVERE, null, ex);
        }
      
 
    }
}
