package diagsys;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Mr Olayinka
 */
public class Search extends javax.swing.JDialog {

   
     ResultSet rs=null ;
     Connection conn = null;
      Statement st = null;
      
    public Search(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       
        initComponents();
        jButton1.setBackground(Color.PINK);
         jPanel3.setBackground(Color.decode("#C0C0C0"));
         datebutton.setBackground(Color.decode("#C0C0C0"));
        DiseaseCmb.setVisible(false); 
       DateconTB.setVisible(false);
        RadioDate.setSelected(true);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableS = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        datebutton = new javax.swing.JButton();
        Radiodisease = new javax.swing.JRadioButton();
        RadioDate = new javax.swing.JRadioButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        DateconTB = new javax.swing.JTextField();
        DiseaseCmb = new javax.swing.JComboBox();
        lblpatient = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Patient");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TableS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableS);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        datebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagsys/find0.png"))); // NOI18N
        datebutton.setToolTipText("Search");
        datebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datebuttonActionPerformed(evt);
            }
        });

        Radiodisease.setText("By Disease");
        Radiodisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiodiseaseActionPerformed(evt);
            }
        });

        RadioDate.setText(" By Date");
        RadioDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDateActionPerformed(evt);
            }
        });

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        DiseaseCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<select disease>", "Malaria", "Typhoid Fever", "Gastroenteritis" }));
        DiseaseCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DiseaseCmbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Radiodisease)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DiseaseCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioDate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateconTB, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Radiodisease)
                        .addComponent(RadioDate)
                        .addComponent(datebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DateconTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DiseaseCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagsys/go.png"))); // NOI18N
        jButton1.setText("Check disease statistics");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jXSearchField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jXSearchField1CaretUpdate(evt);
            }
        });
        jXSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXSearchField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpatient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("M/d/yyyy");
        String s = sdf.format(jXDatePicker1.getDate());
       DateconTB.setText(s);
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void RadiodiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiodiseaseActionPerformed
      
//        RadioAbsentees.setSelected(false);
        RadioDate.setSelected(false);
        lblpatient.setText("");
        DiseaseCmb.setVisible(true); 
         DiseaseCmb.requestFocus(); 
        jXDatePicker1.setVisible(false);
        datebutton.setVisible(false);
        DiseaseCmb.setSelectedIndex(0);
               DefaultTableModel dtm = (DefaultTableModel) TableS.getModel();
                dtm.setRowCount(0);
                dtm.setColumnCount(0);
       
    }//GEN-LAST:event_RadiodiseaseActionPerformed

    private void RadioDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDateActionPerformed
    Radiodisease.setSelected(false);
        DiseaseCmb.setVisible(false); 
        jXDatePicker1.setVisible(true);
        datebutton.setVisible(true);  
         lblpatient.setText("");
        
        DefaultTableModel dtm = (DefaultTableModel) TableS.getModel();
                dtm.setRowCount(0);
                dtm.setColumnCount(0);
    }//GEN-LAST:event_RadioDateActionPerformed

    private void datebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datebuttonActionPerformed
     
        if (DateconTB.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please choose date!!");
           return;
        }
        
        try {
            conn = SqlConnect.conDB();
            st = conn.createStatement();
            
            String p ="select Name,Gender,Age,Diagnosis_Result,Drug_Prescription from Patientinfo where Diagnosis_Date='"+DateconTB.getText()+"'";
            rs = st.executeQuery(p);
            TableS.setModel(DbUtils.resultSetToTableModel(rs));
            lblpatient.setText("No of patient diagnosed on " +DateconTB.getText()+ " : "+TableS.getRowCount());
            rs.close();
            st.close();
          
        } catch (SQLException | IOException ex) {
             JOptionPane.showMessageDialog(this,ex);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
             JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_datebuttonActionPerformed

    private void DiseaseCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DiseaseCmbItemStateChanged
        // TODO add your handling code here:
        
        if (DiseaseCmb.getSelectedItem() == "<select disease>") {     
               
            lblpatient.setText("");
            DefaultTableModel dtm = (DefaultTableModel) TableS.getModel();
            dtm.setRowCount(0);
           dtm.setColumnCount(0);
            return;
        }
        
        try {
            conn = SqlConnect.conDB();
            st = conn.createStatement();
       
           String p ="select Name,Gender,Age,Drug_Prescription,Diagnosis_Date from Patientinfo where Diagnosis_Result = '"+DiseaseCmb.getSelectedItem()+"'";
            rs = st.executeQuery(p);
            TableS.setModel(DbUtils.resultSetToTableModel(rs));         
             lblpatient.setText("No of patient diagnosed with " +DiseaseCmb.getSelectedItem()+ " : "+TableS.getRowCount());
            rs.close();
            st.close();
          
        } catch (SQLException | IOException ex) {
             JOptionPane.showMessageDialog(this,ex);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
             JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_DiseaseCmbItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
     try {
            conn = SqlConnect.conDB();
            st = conn.createStatement();
            
          DefaultCategoryDataset dataset =  new DefaultCategoryDataset( );
           String Mal = "select Diagnosis_Result, count(Diagnosis_Result) from Patientinfo where Diagnosis_Result = 'Malaria' ";
           String Gast = "select Diagnosis_Result, count(Diagnosis_Result) from Patientinfo where Diagnosis_Result = 'Typhoid Fever' ";
           String Ty = "select Diagnosis_Result, count(Diagnosis_Result) from Patientinfo where Diagnosis_Result = 'Gastroenteritis' ";
          
            rs = st.executeQuery(Mal);
            int malariacount = 0;
            while (rs.next()){ malariacount = rs.getInt("count(Diagnosis_Result)");}
            
            int typhoidcount = 0;
            rs = st.executeQuery(Gast);
            while (rs.next()){ typhoidcount = rs.getInt("count(Diagnosis_Result)");}
                    
            int gastrocount = 0;
            rs = st.executeQuery(Ty);          
            while (rs.next()){ gastrocount = rs.getInt("count(Diagnosis_Result)");}
             
            dataset.addValue(malariacount , "Malaria" ,"Malaria");
            dataset.addValue(typhoidcount , "Typhoid Fever" ,"Typhoid Fever");
            dataset.addValue(gastrocount , "Gastroenteritis" ,"Gastroenteritis");
            
              JFreeChart barChart = ChartFactory.createBarChart3D(
                "No of patient(s) diagnosed with",
                "Diseases ",
                "",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, true);
            barChart.setBackgroundPaint(Color.decode("#a9ba9d"));
          
            
            ChartFrame chartPanel = new ChartFrame("Diagnosis Statistics", barChart );
            chartPanel.setSize(600, 470);
            chartPanel.setLocationRelativeTo(null);  
           this.dispose();
            chartPanel.setVisible(true);
            chartPanel .addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent evt) {
                   
                    Search g = new Search(null , false);
                    g.setVisible(true);
                };
            });

             
           rs.close();
            st.close();
          
        } catch (SQLException | IOException |ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
             JOptionPane.showMessageDialog(this,ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jXSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXSearchField1ActionPerformed
        // TODO add your handling code here:
        try {
            conn = SqlConnect.conDB();
            st = conn.createStatement();
       
           String p ="select Name,Gender,Age,Drug_Prescription,Diagnosis_Date from Patientinfo where Diagnosis_Result = '"+jXSearchField1.getText()+"'";
            rs = st.executeQuery(p);
            if (rs.next()) {
                TableS.setModel(DbUtils.resultSetToTableModel(rs));   
                 lblpatient.setText("No of patient diagnosed with " +jXSearchField1.getText()+ " : "+TableS.getRowCount());
            }else{ 
            DefaultTableModel dtm = (DefaultTableModel) TableS.getModel();
            dtm.setRowCount(0);
            dtm.setColumnCount(0);
            lblpatient.setText("");
                          }
                
            rs.close();
            st.close();
          
        } catch (SQLException | IOException ex) {
             JOptionPane.showMessageDialog(this,ex);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
             JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_jXSearchField1ActionPerformed

    private void jXSearchField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jXSearchField1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jXSearchField1CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Search dialog = new Search(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateconTB;
    private javax.swing.JComboBox DiseaseCmb;
    private javax.swing.JRadioButton RadioDate;
    private javax.swing.JRadioButton Radiodisease;
    private javax.swing.JTable TableS;
    private javax.swing.JButton datebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private javax.swing.JLabel lblpatient;
    // End of variables declaration//GEN-END:variables
}
